# Stage 1: Build stage
FROM mcr.microsoft.com/windows/servercore:ltsc2022 AS builder

# Set the working directory
WORKDIR /promtail

# Set build argument for Promtail version
ARG PROMTAIL_VERSION=2.8.2

# Download and extract Promtail
ADD https://github.com/grafana/loki/releases/download/v${PROMTAIL_VERSION}/promtail-windows-amd64.exe.zip .
RUN powershell -Command Expand-Archive promtail-windows-amd64.exe.zip -DestinationPath .

# Stage 2: Final stage
FROM mcr.microsoft.com/windows/nanoserver:ltsc2022

# Set labels
LABEL \
    Owner="Muhammed Iqbal" \
    Base="Windows Nano Server LTSC 2022" \
    Application="Promtail" \
    Version=${PROMTAIL_VERSION}

# Set the working directory
WORKDIR /promtail

# Copy the Promtail binary from the builder stage
COPY --from=builder /promtail/promtail-windows-amd64 .

# Expose the necessary ports
EXPOSE 3101

# Set the command to run Promtail
ENTRYPOINT ["promtail-windows-amd64"]

